nome=input("Digite o nome do funcionário: ")
empresa=input("Digite a instituição: ")
qtdFuncionarios=int(input("Digite a quantidade de funcionários: "))
mediaMensalidade=float(input("Digite a média de mensalidade: "))
print(nome + " trabalha na empresa " + empresa)
print("Possue: ", qtdFuncionarios, "funcionários. ")
print("A média da mensalidade é de: " + str(mediaMensalidade))
print("==========Verifique os tipos de dados abaixo:==========")
print("O tipo de dado da variável [nome] é: ", type(nome))
print("O tipo de dado da variável [empresa] é: ", type(empresa))
print("O tipo de dado da variável [qtdFuncionarios] é: ", type(qtdFuncionarios))
print("O tipo de dado da variável [mediaMensalidade] é: ", type(mediaMensalidade))
